<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-12-01T05:23:14 GMT-08:00" name="Suite" finished-at="2023-12-01T05:23:15 GMT-08:00" duration-ms="1590">
    <groups>
    </groups>
    <test started-at="2023-12-01T05:23:14 GMT-08:00" name="Test" finished-at="2023-12-01T05:23:15 GMT-08:00" duration-ms="1590">
      <class name="com.selenium.Projecr2.NewTest">
        <test-method signature="test1()[pri:0, instance:com.selenium.Projecr2.NewTest@957e06]" started-at="2023-12-01T05:23:14 GMT-08:00" name="test1" finished-at="2023-12-01T05:23:14 GMT-08:00" duration-ms="169" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method signature="test2()[pri:0, instance:com.selenium.Projecr2.NewTest@957e06]" started-at="2023-12-01T05:23:14 GMT-08:00" name="test2" finished-at="2023-12-01T05:23:14 GMT-08:00" duration-ms="14" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method signature="test3()[pri:0, instance:com.selenium.Projecr2.NewTest@957e06]" started-at="2023-12-01T05:23:14 GMT-08:00" name="test3" finished-at="2023-12-01T05:23:15 GMT-08:00" duration-ms="1025" status="FAIL">
          <exception class="org.testng.internal.thread.ThreadTimeoutException">
            <message>
              <![CDATA[Method com.selenium.Projecr2.NewTest.test3() didn't finish within the time-out 1000]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.selenium.Projecr2.NewTest.test3() didn't finish within the time-out 1000
at java.base@17.0.8.1/java.lang.Thread.sleep(Native Method)
at app//com.selenium.Projecr2.NewTest.test3(NewTest.java:23)
at java.base@17.0.8.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@17.0.8.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base@17.0.8.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@17.0.8.1/java.lang.reflect.Method.invoke(Method.java:568)
at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base@17.0.8.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@17.0.8.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17.0.8.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17.0.8.1/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.thread.ThreadTimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
        <test-method signature="test4()[pri:0, instance:com.selenium.Projecr2.NewTest@957e06]" started-at="2023-12-01T05:23:15 GMT-08:00" name="test4" finished-at="2023-12-01T05:23:15 GMT-08:00" depends-on-methods="com.selenium.Projecr2.NewTest.test3" duration-ms="1" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method com.selenium.Projecr2.NewTest.test4() on instance com.selenium.Projecr2.NewTest@957e06 depends on not successfully finished methods 
[com.selenium.Projecr2.NewTest.test3() on instance com.selenium.Projecr2.NewTest@957e06]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method com.selenium.Projecr2.NewTest.test4() on instance com.selenium.Projecr2.NewTest@957e06 depends on not successfully finished methods 
[com.selenium.Projecr2.NewTest.test3() on instance com.selenium.Projecr2.NewTest@957e06]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:150)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test4 -->
      </class> <!-- com.selenium.Projecr2.NewTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
